services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=task_management'
      - 'POSTGRES_PASSWORD=1974'
      - 'POSTGRES_USER=ojasva'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql_versions:/flyway/sql
      - ./docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local