FROM openjdk:21
WORKDIR /app
COPY build/libs/task_management_backend-0.0.1-SNAPSHOT.jar /app/task_management_backend-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/task_management_backend-0.0.1-SNAPSHOT.jar"]
